language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - nightly
notifications:
    email: false
sudo: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone("https://github.com/JuliaNLSolvers/NLSolversBase.jl.git")'
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.checkout("NLSolversBase", "pkm/refactor")'
    - julia -e 'Pkg.add("LineSearches")' # Necessary?
    - julia -e 'Pkg.checkout("LineSearches", "newdf2")'
    - julia -e 'Pkg.test("Optim", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Optim")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("Optim")); include(joinpath("docs", "make.jl"))'
